### ISSUE TITLE
migrate UserRoles

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-office-workflow#476]
Migrate to the core imixs-workflow user group names.
See also /imixs/imixs-marty/issues/373

**Todos**

- [x] Upgrade to imixs-marty 4.2.1
- [x] remove the usergroups field in the SetupControler init() method
- [x] provide a static select item list providing the new core roles and user friendly names
- [x] Replace the UI group selection in the profile page with a static radio button list
